# Generated by Django 5.1.7 on 2025-03-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_alter_emprestimos_mome_emprestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
    ]
